// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: test_data/test.proto

package grpc_fts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestService_ClientStreamMethod_FullMethodName = "/test.TestService/ClientStreamMethod"
	TestService_ServerStreamMethod_FullMethodName = "/test.TestService/ServerStreamMethod"
	TestService_BidiStreamMethod_FullMethodName   = "/test.TestService/BidiStreamMethod"
	TestService_UnaryMethod_FullMethodName        = "/test.TestService/UnaryMethod"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	ClientStreamMethod(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TestMessage, TestMessage], error)
	ServerStreamMethod(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TestMessage], error)
	BidiStreamMethod(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TestMessage, TestMessage], error)
	UnaryMethod(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) ClientStreamMethod(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TestMessage, TestMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], TestService_ClientStreamMethod_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestMessage, TestMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_ClientStreamMethodClient = grpc.ClientStreamingClient[TestMessage, TestMessage]

func (c *testServiceClient) ServerStreamMethod(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TestMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[1], TestService_ServerStreamMethod_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestMessage, TestMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_ServerStreamMethodClient = grpc.ServerStreamingClient[TestMessage]

func (c *testServiceClient) BidiStreamMethod(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TestMessage, TestMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[2], TestService_BidiStreamMethod_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TestMessage, TestMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_BidiStreamMethodClient = grpc.BidiStreamingClient[TestMessage, TestMessage]

func (c *testServiceClient) UnaryMethod(ctx context.Context, in *TestMessage, opts ...grpc.CallOption) (*TestMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestMessage)
	err := c.cc.Invoke(ctx, TestService_UnaryMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
type TestServiceServer interface {
	ClientStreamMethod(grpc.ClientStreamingServer[TestMessage, TestMessage]) error
	ServerStreamMethod(*TestMessage, grpc.ServerStreamingServer[TestMessage]) error
	BidiStreamMethod(grpc.BidiStreamingServer[TestMessage, TestMessage]) error
	UnaryMethod(context.Context, *TestMessage) (*TestMessage, error)
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) ClientStreamMethod(grpc.ClientStreamingServer[TestMessage, TestMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamMethod not implemented")
}
func (UnimplementedTestServiceServer) ServerStreamMethod(*TestMessage, grpc.ServerStreamingServer[TestMessage]) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamMethod not implemented")
}
func (UnimplementedTestServiceServer) BidiStreamMethod(grpc.BidiStreamingServer[TestMessage, TestMessage]) error {
	return status.Errorf(codes.Unimplemented, "method BidiStreamMethod not implemented")
}
func (UnimplementedTestServiceServer) UnaryMethod(context.Context, *TestMessage) (*TestMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryMethod not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call pancis, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_ClientStreamMethod_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).ClientStreamMethod(&grpc.GenericServerStream[TestMessage, TestMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_ClientStreamMethodServer = grpc.ClientStreamingServer[TestMessage, TestMessage]

func _TestService_ServerStreamMethod_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).ServerStreamMethod(m, &grpc.GenericServerStream[TestMessage, TestMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_ServerStreamMethodServer = grpc.ServerStreamingServer[TestMessage]

func _TestService_BidiStreamMethod_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).BidiStreamMethod(&grpc.GenericServerStream[TestMessage, TestMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_BidiStreamMethodServer = grpc.BidiStreamingServer[TestMessage, TestMessage]

func _TestService_UnaryMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).UnaryMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_UnaryMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).UnaryMethod(ctx, req.(*TestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryMethod",
			Handler:    _TestService_UnaryMethod_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStreamMethod",
			Handler:       _TestService_ClientStreamMethod_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreamMethod",
			Handler:       _TestService_ServerStreamMethod_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidiStreamMethod",
			Handler:       _TestService_BidiStreamMethod_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "test/test.proto",
}
